Fix sprintf warning
ir33k/gmi100 pull request #5
Opened 2024-10-28 19:28 UTC by arabusov

With gcc version 14.2.1 I got the following warning:

gmi100.c:51:33: warning: ‘%s’ directive writing up to 1024 bytes into a region of size between 1 and 1025 [-Wformat-overflow=]
   51 |                 sprintf(buf, "%s%s", uri, bp);
      |                                 ^~
gmi100.c:51:17: note: ‘sprintf’ output between 1 and 2049 bytes into a
destination of size 1025
   51 |                 sprintf(buf, "%s%s", uri, bp);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Uri and bp point to two character arrays of size 1025 both, thus the destination should be twice larger.

2024-10-28 19:33 UTC, arabusov commented
Also, important for this project:

```
$ git rev-parse --short HEAD
b3e7841
$ wc -l gmi100.c 
100 gmi100.c
```

2024-10-28 20:17 UTC, ir33k requested changes
Thanks for contribution.
Yes, you are absolutely right.
I also got this error.
I'm not sure why it was not there last time when I was compiling.

2024-10-28 20:17 UTC, ir33k commented on gmi100.c
> +        char uri[1024+1], buf[2*(1024+1)], buf2[1024+1], *bp, *t=tmpnam(0);
Yep, this works.
I think that we could just use bigger buffers.
The 4096 is a default for many internal POSIX functions, at least in glibc.

The `+1` in `uri` is only to clearly show that URI max length is 1024 according to Gemini specification `+1` for null terminator.

```suggestion
        char uri[1024+1], buf[4096], buf2[2048], *bp, *t=tmpnam(0);
```

2024-10-29 08:30 UTC, merged

2024-10-29 08:31 UTC, ir33k commented
Merged, thanks again